apiVersion: apps/v1
kind: Deployment
metadata:
  name: msgsend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msgsend
  template:
    metadata:
      labels:
        app: msgsend
    spec:
      containers:
        - name: msgsend-container
          image: keyssong/msgsend:latest  # ðŸ”¹ Buscar no Docker Hub
          imagePullPolicy: Always           # ðŸ”¹ Sempre buscar a versÃ£o mais recente
          ports:
            - containerPort: 8088
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
